# Generated by Django 2.2 on 2022-10-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Auth_detail',
            field=models.TextField(null=True),
        ),
    ]
