# Generated by Django 2.2 on 2022-10-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_post_auth_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
