# Generated by Django 2.2 on 2022-10-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Auth_detail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
