# Generated by Django 2.2 on 2022-10-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20221027_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='s',
            field=models.ImageField(default='Some String', upload_to='images/'),
        ),
    ]
