# Generated by Django 2.2 on 2022-10-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20221027_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='s',
            new_name='image',
        ),
    ]
